### ISSUE TITLE
No module named scraper.Crawl

### ISSUE THREAD

**Issue by tjnine** [dvlden/TutsRape#1]
Hey, great script...anyway I followed the instructions and when running $ python init.py I get the following error.

'''
Traceback (most recent call last):
  File "init.py", line 2, in <module>
    from scraper.Crawl import Crawl
ImportError: No module named scraper.Crawl

**Comment by nnx0r** [comment]
I am on macOS Sierra, so I am using Homebrew for any installations. 
I do get the same thing when I run `python init.py` in the console, because by default on macOS there's Python v2.7.10

So via Homebrew, I installed Python 3 and then I need to use pip3 and python3 commands instead.

Here's first example of default preinstalled python that comes with macOS:
<img width="309" alt="screen shot 2017-04-05 at 20 44 37" src="https://cloud.githubusercontent.com/assets/3460368/24721600/1b7bcf14-1a41-11e7-9aa5-ca1ed8417a91.png">

And here's the one with newest Python installed via Homebrew:
<img width="224" alt="screen shot 2017-04-05 at 20 45 31" src="https://cloud.githubusercontent.com/assets/3460368/24721609/28b672b0-1a41-11e7-9931-4fd0bc54a8fe.png">

That one works fine... Please double check and then provide me some more information if it still does not work.

```
OS and version:
Python version:
```

**Comment by tjnine** [comment]
Hey, thanks for the quick reply. 

OS => OSX El Capitain v10.11.6
Python => Python 2.7.10 & Python 3.6.1

I get a new warning now after trying $ python3 init.py
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/nn/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "init.py", line 5, in <module>
    Crawl()
  File "/Users/teejten/PythonProjects/TutsRape/scraper/Crawl.py", line 17, in __init__
    self.driver = Helper.setup_webdriver()
  File "/Users/teejten/PythonProjects/TutsRape/scraper/Helper.py", line 39, in setup_webdriver
    return webdriver.Chrome(driver_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

FYI...I added chromedriver to my path and I still get the same errors. Do you think I should add my path to the python script via 
 driver = webdriver.Chrome('/path/to/chromedriver')

**Comment by tjnine** [comment]
Sorry to flood your repo with stupidity...I updated the python script with the correct path to chromedriver and am getting a new error. Also just to note I installed chromedriver via homebrew.

```
Traceback (most recent call last):
  File "init.py", line 5, in <module>
    Crawl()
  File "/Users/teejten/PythonProjects/TutsRape/scraper/Crawl.py", line 17, in __init__
    self.driver = Helper.setup_webdriver()
  File "/Users/teejten/PythonProjects/TutsRape/scraper/Helper.py", line 39, in setup_webdriver
    return webdriver.Chrome(driver_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: session not created exception: Chrome version must be >= 56.0.2884.0
  (Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.11.6 x86_64)

**Comment by nnx0r** [comment]
Yes, you should define Chrome driver path in config file.

Please download chromedriver from: https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by tjnine** [comment]
I defined the path and I am getting the same errors as I posted above. Since I installed with homebrew I used the path where homebrew insalled it.

**Comment by nnx0r** [comment]
Well, as I said. Seems like Homebrew does not install latest version, as in the output of your Error message you can see:

`Message: session not created exception: Chrome version must be >= 56.0.2884.0`

**Comment by tjnine** [comment]
yeah, I noticed that too but when I tried to install chromedriver with the link you gave me I the file kept saying the file was corrupt....?
